# Generated by Django 6.0.3 on 2026-03-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp32_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_index', models.IntegerField(choices=[(0, 'Outlet 0'), (1, 'Outlet 1'), (2, 'Outlet 2'), (3, 'Outlet 3')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('esp32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='extended_app.esp32')),
            ],
            options={
                'unique_together': {('esp32', 'outlet_index')},
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amperage', models.FloatField()),
                ('volts', models.FloatField()),
                ('watts', models.FloatField()),
                ('timestamp_ms', models.BigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='extended_app.outlet')),
            ],
            options={
                'ordering': ['timestamp_ms'],
            },
        ),
    ]
