# Generated by Django 6.0.3 on 2026-03-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='powerreading',
            old_name='volts',
            new_name='voltage',
        ),
        migrations.RenameField(
            model_name='powerreading',
            old_name='watts',
            new_name='wattage',
        ),
    ]
