# Generated by Django 6.0.3 on 2026-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0002_rename_volts_powerreading_voltage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerreading',
            options={'ordering': ['projected_timestamp']},
        ),
        migrations.AddField(
            model_name='powerreading',
            name='button_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='projected_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
