# Generated by Django 6.0.3 on 2026-03-13 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0003_alter_powerreading_options_powerreading_button_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('compact_flourescent_lamp', 'Compact Flourescent Lamp'), ('air_conditioner', 'Air Conditioner'), ('hairdryer', 'Hairdryer'), ('laptop', 'Laptop'), ('vacuum', 'Vacuum'), ('fridge', 'Fridge'), ('washing_machine', 'Washing Machine'), ('incandescent_light_bulb', 'Incandescent Light Bulb'), ('microwave', 'Microwave'), ('fan', 'Fan'), ('heater', 'Heater'), ('coffee_maker', 'Coffee Maker'), ('water_kettle', 'Water Kettle'), ('hair_iron', 'Hair Iron'), ('soldering_iron', 'Soldering Iron'), ('blender', 'Blender')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_type', to='extended_app.outlet')),
            ],
        ),
    ]
