# Generated by Django 6.0.3 on 2026-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0004_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerreading',
            name='max_voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='min_voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
