# Generated by Django 5.2.12 on 2026-03-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0005_alter_device_id_alter_esp32_id_alter_outlet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerreading',
            name='max_voltage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='min_voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
