# Generated by Django 5.2.12 on 2026-03-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extended_app', '0005_powerreading_max_voltage_powerreading_min_voltage'),
        ('extended_app', '0006_powerreading_max_voltage_powerreading_min_voltage'),
    ]

    operations = [
    ]
